apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-application-set
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    eks.myheritage.com/band: 'devops'
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'prometheus-{{ .name }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        eks.myheritage.com/parent-applicationset: prometheus-application-set
        eks.myheritage.com/band: 'devops'
    spec:
      destination:
        server: '{{ .server }}'
        namespace: kube-system
      project: default
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          targetRevision: 25.30.1
          chart: prometheus-community/prometheus
